[#top-preface-introduction]
= Introduction

ifndef::include-only-once[]
:root-path: ../
:imagesdir: {root-path}/_images
:includedir: {root-path}/_images
include::{root-path}_config.adoc[]
endif::[]

:sectnums!:

== Overview

// include::1_1_Overview.adoc[]
//
// include::1_2_Conventions.adoc[]
//
// include::1_3_Normative_and_non_norm_stats.adoc[]
//
// include::1_4_Deliverables_of_the_OpenCRG_Spec.adoc[]

=== Modal verbs

To ensure compliance with the OpenCRG standard, users must be able to distinguish between mandatory requirements, recommendations, permissions, as well as possibilities, capabilities, obligations and necessities.

The following rules for using modal verbs apply:

[#tab-modal-verbs]
.Rules for using modal verbs
[%header, cols=2*]
|===
|Provision									|Verbal form
|*Requirement* +
Requirements shall be followed strictly in order to be conform to the standard. Deviations are not allowed.
|shall +
shall not

|*Recommendation* +
Recommendations indicate that among several possibilities, one is recommended as particularly suitable, without mentioning or excluding others.
|should +
should not

|*Permission* +
Permissions indicate a course of action permissible within the limits of OpenCRG deliverables.
|may +
need not

|*Possibility and capability* +
These verbal forms are used for stating possibilities or capabilities, being technical, material, physical, or others.
|can +
can not

|*Obligation and necessity* +
These verbal forms are used to describe legal, organizational, or technical obligations and necessities that are not regulated or enforced by the OpenCRG standard.
|must +
must not
|===

=== Typographic conventions

This documentation uses the following typographical conventions:

[#tab-typographic-conventions]
.Typographical conventions
[%header, cols=2*]
|===
|Mark-up					|Definition
|`Code elements`			|This format is used for code elements, such as technical names of classes and attributes, as well as attribute values.
|```[blue]#Code snippets#``` 				|This format is used for excerpts of code that serve as an example for implementation.
|_Terms_						|This format is used to introduce glossary terms, new terms and to emphasize terms.
|`[green]#Mathematical elements#`	|This format is used for calculations and mathematical elements.
|===