[#top-scope-scope]
= Scope

ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]

{THIS_STANDARD} specifies the modeling approach for describing high-fidelity road surfaces (micro-topography) for driving and tire simulation applications.
The standard has the following scope:

*Data Structure and Representation*

- Specify the Curved Regular Grid (CRG) data format for representing 3D road surface data (elevation, friction, and other properties) relative to a curved reference line.
- Define the binary and ASCII file formats used to store large-scale, high-resolution surface scans efficiently.

*Tools and APIs*

- Provide a standardized C-API for reading and evaluating CRG data within simulation environments.
- Provide a MATLAB tool suite for the creation, modification, and validation of ASAM OpenCRG data sets.

:sectnums:
:tableoffset: 8
[#tab-test]
.Test table
[frame="none]
|===
|User guide| The User Guides help to get started with the OpenCRG APIs and how OpenCRG can be applied
|Sample OpenCRG files| These demo files are explanatory examples
|C-API including demo files and test scripts| The C-API is capable of reading and evaluating OpenCRG Files
|MATLAB library including demo files and test scripts| The Matlab API can create, manipulate, visualize and validate OpenCRG Files
|===