name: Build Specification

on:
  workflow_call:
    outputs:
      specification-html-filepath:
        description: "Path to the built HTML specification"
        value: ${{ jobs.build.outputs.specification-html-filepath }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      specification-html-filepath: ${{ steps.build-spec.outputs.specification-html-filepath }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          gem install asciidoctor asciidoctor-diagram

      - name: Build specification
        id: build-spec
        env:
          SPECIFICATION_DOC_FILEPATH: "${{vars.SPECIFICATION_DOC_FILEPATH}}"
          SPECIFICATION_RELEASE_DIR: "${{vars.SPECIFICATION_RELEASE_DIR}}"
        run: |
          # Derive path to specification html file
          SPECIFICATION_BASENAME="${SPECIFICATION_DOC_FILEPATH##*/}"
          SPECIFICATION_BASENAME="${SPECIFICATION_BASENAME%.*}"
          SPECIFICATION_HTML_FILEPATH=$SPECIFICATION_RELEASE_DIR/"$SPECIFICATION_BASENAME.html"
          
          # Build specification
          mkdir -p "$SPECIFICATION_RELEASE_DIR"
          asciidoctor -r asciidoctor-diagram "$SPECIFICATION_DOC_FILEPATH" -o "$SPECIFICATION_HTML_FILEPATH"
          
          # Copy specification to subdirectory for pages upload
          PAGES_DIR=$SPECIFICATION_RELEASE_DIR/"pages"
          mkdir -p "$PAGES_DIR"
          cp "$SPECIFICATION_HTML_FILEPATH" "$PAGES_DIR/index.html"
          
          echo "PAGES_DIR=$PAGES_DIR" >> "$GITHUB_ENV"
          echo "specification-html-filepath=$SPECIFICATION_HTML_FILEPATH" >> "$GITHUB_OUTPUT"
          

      - name: Upload specification artifact
        uses: actions/upload-artifact@v6
        with:
          name: specification-artifact
          path: ${{ steps.build-spec.outputs.specification-html-filepath }}


      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: specification-pages-artifact
          path: ${{ env.PAGES_DIR }}
